/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.consoleExample;

import com.google.common.io.Files;
import com.my.*;
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.DataOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.OutputStreamWriter;
import java.net.InetAddress;
import java.net.ServerSocket;
import java.net.Socket;
import java.net.SocketException;
import java.net.UnknownHostException;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import java.util.concurrent.Callable;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.TimeoutException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import org.apache.commons.cli.*;




public class App {
  static Gson gson = new GsonBuilder().setPrettyPrinting().create();
  static Scanner scan = new Scanner(System.in);
  static JsonActions jAct = new JsonActions();
    
    
    
  public static void main(String[] args) throws IOException {
    AppConfig config = new AppConfig();
    Options options = config.configureOptions();
    config.optionsExecution(options, args);
    ExecutorService exec = Executors.newFixedThreadPool(4);
    Integer port = 7777;
    ServerSocket serverSocket = new ServerSocket(port);
    
    Runnable runnableTask = () -> {
      try {
        TimeUnit.MILLISECONDS.sleep(10);
      } catch (InterruptedException ex) {
        Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
      }
    };
    
    
    Callable<Socket> serverTimerCheck = () -> {
      return serverSocket.accept();
    };
    
    Runnable serverStart = () -> {
      try {
        while (!Thread.currentThread().isInterrupted()){
          System.out.println("waiting for connection");
          Future<Socket> check = exec.submit(serverTimerCheck);

          exec.submit(new ServerThread(port, serverSocket, check.get(30, TimeUnit.SECONDS)));
          
        }
        serverSocket.close();
      } catch (IOException | InterruptedException | ExecutionException ex) {
        Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
      } catch (TimeoutException ex) {
        try {
          serverSocket.close();
          exec.shutdown();
        } catch (IOException ex1) {
          Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex1);
        }
        Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
      }
    };
    Callable<String> callableTask = () -> {
      TimeUnit.MILLISECONDS.sleep(20);
      return "callable task done";
    };
    List<Callable<String>> taskList = new ArrayList<>();
    taskList.add(callableTask);
    taskList.add(callableTask);
    taskList.add(callableTask);
    
    
    Future<?> task = exec.submit(serverStart);
    try {
      //exec.invokeAll(taskList);
      System.out.println(exec.submit(callableTask).get());
      exec.submit(callableTask);
      exec.submit(callableTask);
      exec.execute(runnableTask);
      //task.get(30, TimeUnit.SECONDS);
    } catch (InterruptedException ex) {
        //serverSocket.close();
        //exec.shutdownNow();

      Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
    } catch (ExecutionException ex) {
      Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
    }
  }
}






class ServerThread implements Runnable{
  ServerSocket serverSocket;
  Socket clientSocket;
  ObjectOutputStream out;
  BufferedReader in;
  int port;
  String fileName;
  String filePath;
  

  public ServerThread(int port, ServerSocket serverSocket, Socket clientSocket) {
      this.port = port;
      this.serverSocket = serverSocket;
      this.clientSocket = clientSocket;
      fileName = "telemetry_data_1.json";
      filePath = "C:\\Users\\Andrei\\Documents\\ConsoleExampleDocs\\";
      
  }
  
  @Override
  public void run(){
    try {
      out = new ObjectOutputStream(clientSocket.getOutputStream());
      in = new BufferedReader(new InputStreamReader(clientSocket.getInputStream()));
      System.out.println("server: reading input");
      String[] meta = in.readLine().split(" ");
      

      if (meta[0].equals("send")){
        System.out.println("server: getting values");
        String json = in.lines().collect(Collectors.joining());
        fileName = String.format("telemetry_data_%s.json", meta[1]);
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(filePath + fileName))){
          writer.write(json);
        } catch (Exception e) {
        }
      }

      else if (meta[0].equals("get")){
        fileName = String.format("telemetry_data_%s", meta[1]);
        try (BufferedReader reader = new BufferedReader(new FileReader(filePath + fileName))) {
          System.out.println("server: sending values");
          out.writeObject(reader.readLine());
          System.out.println("server: values sent");
        } catch (Exception e) {
        }
        
        out.flush();
      }

      else {
        out.writeBytes("unknown connection");
        System.out.println("server: meta error");
      }

    } catch (IOException ex) {
      Logger.getLogger(ServerThread.class.getName()).log(Level.SEVERE, null, ex);
    }
    System.out.println();
  }
}



